"""Time-stepping schemes for the Caputo fractional Bloch equations.

All schemes approximate the Caputo derivative on a uniform grid x_n = x_0 + n h by
a discrete convolution

    D^alpha u (x_n)  ~  h^(-alpha) * sum_{j=0}^{n} w_{n-j} (u_j - u_0),

with either
  * 'bdf2' : second-order convolution-quadrature weights generated by
             (3/2 - 2 z + z^2/2)^alpha  (Lubich), with the single-step starting
             correction of Jin, Li & Zhou (SIAM J. Sci. Comput. 39 (2017) A3129),
  * 'l1'   : the classical L1 formula rewritten in the same form
             (w_0 = 1/Gamma(2-alpha), w_m = (a_m - a_{m-1})/Gamma(2-alpha),
              a_m = (m+1)^(1-alpha) - m^(1-alpha)).

Models (fractional order alpha in (0, 1); alpha = 1 is handled by `solve_markov`)
  fixed      : Caputo equation in the fixed pseudospin basis (reference model).
  covariant  : the same dynamics integrated in the instantaneous basis with the explicit
               two-time transporter R(t_n, t_j) inside the history sum.
  naive      : Caputo derivative applied to the instantaneous-basis vector plus the local
               connection (model N1 of the manuscript).
  notransport: covariant history integrand kept, transporter replaced by the identity
               (model N2 of the manuscript).

State arrays have shape (N+1, P, 3) with P the number of parameter points.
"""
import numpy as np
from scipy.integrate import solve_ivp
from scipy.special import gamma as Gamma

from . import model as md


# ----------------------------------------------------------------------------
# convolution weights
# ----------------------------------------------------------------------------
def weights_bdf2(alpha, N):
    """Coefficients of (3/2 - 2 z + z^2/2)^alpha up to z^N (alpha may be negative)."""
    a1, a2 = -4.0 / 3.0, 1.0 / 3.0
    c = np.empty(N + 1)
    c[0] = 1.0
    if N >= 1:
        c[1] = alpha * a1
    for n in range(2, N + 1):
        c[n] = ((alpha - (n - 1)) * a1 * c[n - 1] + (2 * alpha - (n - 2)) * a2 * c[n - 2]) / n
    return c * 1.5 ** alpha


def weights_l1(alpha, N):
    """L1 formula written as h^(-alpha) sum_j w_{n-j} (u_j - u_0)."""
    m = np.arange(N + 1, dtype=float)
    a = (m + 1) ** (1 - alpha) - m ** (1 - alpha)
    w = np.empty(N + 1)
    w[0] = a[0]
    w[1:] = a[1:] - a[:-1]
    return w / Gamma(2 - alpha)


def weights_l1_integral(mu, N):
    """Product-rectangle weights for the Riemann-Liouville integral of order mu:
    I^mu f(x_n) ~ h^mu sum_{j=1}^{n} v_{n-j} f_j,  v_m = ((m+1)^mu - m^mu)/Gamma(1+mu)."""
    m = np.arange(N + 1, dtype=float)
    return ((m + 1) ** mu - m ** mu) / Gamma(1 + mu)


def get_weights(alpha, N, scheme):
    if scheme == 'bdf2':
        return weights_bdf2(alpha, N)
    if scheme == 'l1':
        return weights_l1(alpha, N)
    raise ValueError(scheme)


def get_integral_weights(mu, N, scheme):
    """Weights v with I^mu f(x_n) ~ h^mu sum_{j=0}^{n} v_{n-j} f_j (f_0 term kept)."""
    if scheme == 'bdf2':
        return weights_bdf2(-mu, N)
    if scheme == 'l1':
        return weights_l1_integral(mu, N)
    raise ValueError(scheme)


# ----------------------------------------------------------------------------
# helpers
# ----------------------------------------------------------------------------
def grid(x0, xf, N):
    x = np.linspace(x0, xf, N + 1)
    return x, x[1] - x[0]


def initial_state(x0, prm):
    """Valence-band equilibrium state at x0 in the fixed basis: s = -n(x0)."""
    return -md.n_of_x(x0, prm)


def _hist(w, D, n):
    """sum_{j=1}^{n-1} w_{n-j} D_j for D of shape (N+1, P, 3)."""
    if n <= 1:
        return 0.0
    return np.tensordot(w[n - 1:0:-1], D[1:n], axes=(0, 0))


# ----------------------------------------------------------------------------
# alpha = 1 reference
# ----------------------------------------------------------------------------
def solve_markov(prm, x0, xf, N, basis='fixed', rtol=1e-11, atol=1e-13):
    """Markovian (alpha = 1) solution with an adaptive high-order ODE solver.

    basis='fixed': integrate the fixed-basis equation.
    basis='inst' : integrate the instantaneous-basis equation with the local connection.
    Returns x (N+1,), and the fixed-basis Bloch vectors S (N+1, P, 3).
    """
    x, _ = grid(x0, xf, N)
    P = prm.P
    s0 = initial_state(x0, prm)
    if basis == 'fixed':
        def rhs(z, y):
            M, b = md.gen_fixed(z, prm)
            return (np.einsum('pij,pj->pi', M, y.reshape(P, 3)) + b).ravel()
        y0 = s0
    else:
        def rhs(z, y):
            M, b = md.gen_inst(z, prm, connection=True)
            return (np.einsum('pij,pj->pi', M, y.reshape(P, 3)) + b).ravel()
        y0 = md.to_inst(x0, s0, prm)
    sol = solve_ivp(rhs, (x0, xf), y0.ravel(), t_eval=x, method='DOP853', rtol=rtol, atol=atol)
    S = sol.y.T.reshape(N + 1, P, 3)
    if basis != 'fixed':
        S = np.stack([md.to_fixed(x[i], S[i], prm) for i in range(N + 1)])
    return x, S


# ----------------------------------------------------------------------------
# fractional solvers
# ----------------------------------------------------------------------------
def solve_fixed(alpha, prm, x0, xf, N, scheme='bdf2', s0=None, gen=None):
    """Caputo equation in the fixed basis. Returns x, S (fixed-basis Bloch vectors)."""
    gen = gen or md.gen_fixed
    x, h = grid(x0, xf, N)
    P = prm.P
    w = get_weights(alpha, N, scheme)
    c = prm.tau_m ** (alpha - 1) / h ** alpha
    S = np.empty((N + 1, P, 3))
    S[0] = initial_state(x0, prm) if s0 is None else s0
    D = np.zeros_like(S)                      # D_j = S_j - S_0
    I = np.eye(3)[None]
    for n in range(1, N + 1):
        M, b = gen(x[n], prm)
        rhs = c * w[0] * S[0] - c * _hist(w, D, n) + b
        if n == 1 and scheme == 'bdf2':       # starting correction (Jin, Li & Zhou 2017)
            M0, b0 = gen(x[0], prm)
            rhs = rhs + 0.5 * (np.einsum('pij,pj->pi', M0, S[0]) + b0)
        S[n] = np.linalg.solve(c * w[0] * I - M, rhs[..., None])[..., 0]
        D[n] = S[n] - S[0]
    return x, S


def solve_naive(alpha, prm, x0, xf, N, scheme='bdf2'):
    """Model N1: tau_m^(alpha-1) D^alpha s~ = (Omega~ - chi' e_y) x s~ + relaxation.

    Integrated in the instantaneous basis; returns x and the instantaneous-basis
    Bloch vectors St (N+1, P, 3).
    """
    x, h = grid(x0, xf, N)
    P = prm.P
    w = get_weights(alpha, N, scheme)
    c = prm.tau_m ** (alpha - 1) / h ** alpha
    St = np.empty((N + 1, P, 3))
    St[0] = md.to_inst(x0, initial_state(x0, prm), prm)
    D = np.zeros_like(St)
    I = np.eye(3)[None]
    for n in range(1, N + 1):
        M, b = md.gen_inst(x[n], prm, connection=True)
        rhs = c * w[0] * St[0] - c * _hist(w, D, n) + b
        if n == 1 and scheme == 'bdf2':
            M0, b0 = md.gen_inst(x[0], prm, connection=True)
            rhs = rhs + 0.5 * (np.einsum('pij,pj->pi', M0, St[0]) + b0)
        St[n] = np.linalg.solve(c * w[0] * I - M, rhs[..., None])[..., 0]
        D[n] = St[n] - St[0]
    return x, St


def solve_naive_gauge(alpha, prm, x0, xf, N, gauge_fraction=1.0, scheme='bdf2'):
    """Model N1 formulated with rephased eigenvectors, U -> U exp(-i vartheta sigma_z / 2),

        vartheta(t) = gauge_fraction * int_{t0}^{t} (2 eps / hbar) dt'.

    gauge_fraction = 0 is the real gauge used by `solve_naive`; gauge_fraction = 1 removes the
    dynamical phase (interaction picture). In the rephased frame the Bloch vector is
    s' = Rot_z(-vartheta) s~ and the N1 equation reads

        tau_m^(alpha-1) D^alpha s' = [ (2 eps/hbar - vartheta') z - chi' (sin vartheta, cos vartheta, 0) ] x s'
                                     + relaxation.

    The population (1 + s'_z)/2 is a gauge-invariant observable; its dependence on
    gauge_fraction demonstrates that model N1 is not gauge covariant.
    Returns x and the rephased-frame Bloch vectors (N+1, P, 3).
    """
    from scipy.integrate import cumulative_simpson
    x, h = grid(x0, xf, N)
    P = prm.P
    w = get_weights(alpha, N, scheme)
    c = prm.tau_m ** (alpha - 1) / h ** alpha
    g = np.broadcast_to(np.asarray(prm.g, float), (P,))
    q = np.stack([md.q_of_x(xi, prm) for xi in x])                 # (N+1, P)
    prec = 2.0 * g[None] * np.sqrt(1.0 + q * q)                    # 2 eps / hbar
    vth = gauge_fraction * cumulative_simpson(prec, x=x, axis=0, initial=0.0)
    dchi = np.stack([md.dchi_of_x(xi, prm) for xi in x])
    D3 = np.diag([1.0 / prm.T2, 1.0 / prm.T2, 1.0 / prm.T1])[None]
    b = np.zeros((P, 3)); b[:, 2] = -1.0 / prm.T1

    def gen(n):
        Om = np.stack([-dchi[n] * np.sin(vth[n]), -dchi[n] * np.cos(vth[n]),
                       (1.0 - gauge_fraction) * prec[n]], axis=-1)
        return md.cross_matrix(Om) - D3

    S = np.empty((N + 1, P, 3))
    S[0] = md.to_inst(x0, initial_state(x0, prm), prm)            # vartheta(t0) = 0
    D = np.zeros_like(S)
    I = np.eye(3)[None]
    for n in range(1, N + 1):
        M = gen(n)
        rhs = c * w[0] * S[0] - c * _hist(w, D, n) + b
        if n == 1 and scheme == 'bdf2':
            rhs = rhs + 0.5 * (np.einsum('pij,pj->pi', gen(0), S[0]) + b)
        S[n] = np.linalg.solve(c * w[0] * I - M, rhs[..., None])[..., 0]
        D[n] = S[n] - S[0]
    return x, S


def solve_notransport(alpha, prm, x0, xf, N, scheme='bdf2'):
    """Model N2: transporter replaced by the identity inside the memory integral,

        tau_m^(alpha-1) [ D^alpha s~ + I^(1-alpha) (chi' e_y x s~) ] = Omega~ x s~ + relaxation.

    Returns x and the instantaneous-basis Bloch vectors St.
    """
    x, h = grid(x0, xf, N)
    P = prm.P
    w = get_weights(alpha, N, scheme)
    v = get_integral_weights(1 - alpha, N, scheme)
    c = prm.tau_m ** (alpha - 1) / h ** alpha
    ci = prm.tau_m ** (alpha - 1) * h ** (1 - alpha)
    St = np.empty((N + 1, P, 3))
    St[0] = md.to_inst(x0, initial_state(x0, prm), prm)
    D = np.zeros_like(St)
    G = np.zeros_like(St)                     # G_j = chi'_j e_y x s~_j
    ey = np.zeros((P, 3)); ey[:, 1] = 1.0
    dchi0 = md.dchi_of_x(x[0], prm)
    if scheme == 'bdf2':                      # the product-rectangle rule has no j = 0 term
        G[0] = dchi0[:, None] * np.cross(ey, St[0])
    I = np.eye(3)[None]
    for n in range(1, N + 1):
        M, b = md.gen_inst(x[n], prm, connection=False)
        dchi = md.dchi_of_x(x[n], prm)
        Cy = md.cross_matrix(dchi[:, None] * ey)          # chi'_n [e_y x]
        hist_g = np.tensordot(v[n:0:-1], G[0:n], axes=(0, 0))   # j = 0..n-1
        rhs = c * w[0] * St[0] - c * _hist(w, D, n) - ci * hist_g + b
        if n == 1 and scheme == 'bdf2':
            M0, b0 = md.gen_inst(x[0], prm, connection=False)
            rhs = rhs + 0.5 * (np.einsum('pij,pj->pi', M0, St[0]) + b0)
        A = c * w[0] * I + ci * v[0] * Cy - M
        St[n] = np.linalg.solve(A, rhs[..., None])[..., 0]
        D[n] = St[n] - St[0]
        G[n] = np.einsum('pij,pj->pi', Cy, St[n])
    return x, St


def solve_covariant(alpha, prm, x0, xf, N, scheme='bdf2'):
    """Basis-covariant scheme: instantaneous-basis unknowns, explicit two-time transport.

        tau_m^(alpha-1) h^(-alpha) sum_j w_{n-j} [ Q_{n,j} s~_j - Q_{n,0} s~_0 ]
            = Omega~_n x s~_n + relaxation,     Q_{n,j} = O_y(chi_j - chi_n).

    The transporter is evaluated for every pair (n, j) from the mixing angles; no use is
    made of the fixed-basis factorization, so the comparison with `solve_fixed` is an
    independent test. Returns x and the instantaneous-basis Bloch vectors St.
    """
    x, h = grid(x0, xf, N)
    P = prm.P
    w = get_weights(alpha, N, scheme)
    c = prm.tau_m ** (alpha - 1) / h ** alpha
    chi = np.stack([md.chi_of_x(xi, prm) for xi in x])        # (N+1, P)
    St = np.empty((N + 1, P, 3))
    St[0] = md.to_inst(x0, initial_state(x0, prm), prm)
    I = np.eye(3)[None]
    for n in range(1, N + 1):
        M, b = md.gen_inst(x[n], prm, connection=False)
        d0 = chi[0] - chi[n]
        Q0s0 = np.einsum('pij,pj->pi', md.rot_y(d0), St[0])
        if n > 1:
            dch = chi[1:n] - chi[n][None]                      # (n-1, P)
            cs, sn = np.cos(dch), np.sin(dch)
            Sx, Sy, Sz = St[1:n, :, 0], St[1:n, :, 1], St[1:n, :, 2]
            T = np.stack([cs * Sx + sn * Sz, Sy, -sn * Sx + cs * Sz], axis=-1) - Q0s0[None]
            hist = np.tensordot(w[n - 1:0:-1], T, axes=(0, 0))
        else:
            hist = 0.0
        rhs = c * w[0] * Q0s0 - c * hist + b
        if n == 1 and scheme == 'bdf2':       # starting correction, transported to frame 1
            M0, b0 = md.gen_inst(x[0], prm, connection=False)
            f0 = np.einsum('pij,pj->pi', M0, St[0]) + b0
            rhs = rhs + 0.5 * np.einsum('pij,pj->pi', md.rot_y(d0), f0)
        St[n] = np.linalg.solve(c * w[0] * I - M, rhs[..., None])[..., 0]
    return x, St


def solve_covariant_l1_increments(alpha, prm, x0, xf, N):
    """Covariant L1 scheme in the increment form of the manuscript:

        D^n = 1/(Gamma(2-alpha) h^alpha) sum_{j=0}^{n-1} a_{n-1-j}
              Q_{n,j+1} ( s~_{j+1} - Q_{j+1,j} s~_j ).
    """
    x, h = grid(x0, xf, N)
    P = prm.P
    m = np.arange(N + 1, dtype=float)
    a = (m + 1) ** (1 - alpha) - m ** (1 - alpha)
    c = prm.tau_m ** (alpha - 1) / (Gamma(2 - alpha) * h ** alpha)
    chi = np.stack([md.chi_of_x(xi, prm) for xi in x])
    St = np.empty((N + 1, P, 3))
    St[0] = md.to_inst(x0, initial_state(x0, prm), prm)
    dcov = np.zeros((N, P, 3))                 # covariant increments, stored in frame j+1
    I = np.eye(3)[None]
    for n in range(1, N + 1):
        M, b = md.gen_inst(x[n], prm, connection=False)
        if n > 1:
            dch = chi[1:n] - chi[n][None]      # frames j+1 = 1..n-1 -> frame n
            cs, sn = np.cos(dch), np.sin(dch)
            X, Y, Z = dcov[:n - 1, :, 0], dcov[:n - 1, :, 1], dcov[:n - 1, :, 2]
            T = np.stack([cs * X + sn * Z, Y, -sn * X + cs * Z], axis=-1)
            hist = np.tensordot(a[n - 1:0:-1], T, axes=(0, 0))   # weights a_{n-1-j}, j=0..n-2
        else:
            hist = 0.0
        prev = np.einsum('pij,pj->pi', md.rot_y(chi[n - 1] - chi[n]), St[n - 1])
        rhs = c * a[0] * prev - c * hist + b
        St[n] = np.linalg.solve(c * a[0] * I - M, rhs[..., None])[..., 0]
        dcov[n - 1] = St[n] - prev
    return x, St


# ----------------------------------------------------------------------------
# adiabatic (large-gap) limit of the covariant equation
# ----------------------------------------------------------------------------
def solve_adiabatic(alpha, prm, x0, xf, N, scheme='bdf2'):
    """Scalar geometric-memory equation obtained from the covariant equation when the
    interband coherence is eliminated (Delta/(hbar omega) -> infinity):

        tau_m^(alpha-1)/Gamma(1-alpha) int (t-t')^(-alpha) d/dt'[cos(chi(t')-chi(t)) z(t')] dt'
            = -(z(t) + 1)/T1,        z = s~_z,  z(t0) = -1.

    Returns x and the population n_c = (1 + z)/2, shape (N+1, P).
    """
    x, h = grid(x0, xf, N)
    P = prm.P
    w = get_weights(alpha, N, scheme)
    c = prm.tau_m ** (alpha - 1) / h ** alpha
    chi = np.stack([md.chi_of_x(xi, prm) for xi in x])
    z = np.empty((N + 1, P))
    z[0] = -1.0
    for n in range(1, N + 1):
        c0 = np.cos(chi[0] - chi[n]) * z[0]
        if n > 1:
            T = np.cos(chi[1:n] - chi[n][None]) * z[1:n] - c0[None]
            hist = np.tensordot(w[n - 1:0:-1], T, axes=(0, 0))
        else:
            hist = 0.0
        z[n] = (c * w[0] * c0 - c * hist - 1.0 / prm.T1) / (c * w[0] + 1.0 / prm.T1)
    return x, 0.5 * (1.0 + z)


def adiabatic_first_order(prm, x0, xf, N):
    """First-order (in 1 - alpha) adiabatic-limit population divided by (1 - alpha):

        n_c(t)/(1-alpha) = (1/2) int_{t0}^{t} exp(-(t-t')/T1) S(t') dt',
        S(t) = int_{t0}^{t} sin[chi(t) - chi(t')] chi'(t') / (t - t') dt'.

    Returns x, S (N+1, P) and the population coefficient (N+1, P)."""
    x, h = grid(x0, xf, N)
    chi = np.stack([md.chi_of_x(xi, prm) for xi in x])
    dchi = np.stack([md.dchi_of_x(xi, prm) for xi in x])
    S = np.zeros_like(chi)
    for n in range(1, N + 1):
        dt = (x[n] - x[:n])[:, None]
        f = np.sin(chi[n][None] - chi[:n]) * dchi[:n] / dt       # regular integrand
        # trapezoidal rule on [x0, x_n]; at the upper end the integrand tends to chi'(t)^2
        S[n] = h * (f.sum(axis=0) - 0.5 * f[0] + 0.5 * dchi[n] ** 2)
    coef = np.zeros_like(S)
    e = np.exp(-h / prm.T1)
    for n in range(1, N + 1):
        coef[n] = e * coef[n - 1] + 0.25 * h * (e * S[n - 1] + S[n])
    return x, S, coef


# ----------------------------------------------------------------------------
# convenience wrappers
# ----------------------------------------------------------------------------
def inst_from_fixed(x, S, prm):
    return np.stack([md.to_inst(x[i], S[i], prm) for i in range(len(x))])


def population(model, alpha, prm, x0, xf, N, scheme='bdf2'):
    """Solve the requested model ('fixed', 'covariant', 'naive' = N1, 'notransport' = N2;
    alpha >= 1 gives the Markovian solution) and return the grid x and the Bloch vectors in
    the instantaneous basis, shape (N+1, P, 3); n_c = (1 + St[..., 2]) / 2."""
    if alpha >= 1.0:
        x, S = solve_markov(prm, x0, xf, N)
        St = inst_from_fixed(x, S, prm)
    elif model == 'fixed':
        x, S = solve_fixed(alpha, prm, x0, xf, N, scheme)
        St = inst_from_fixed(x, S, prm)
    elif model == 'naive':
        x, St = solve_naive(alpha, prm, x0, xf, N, scheme)
    elif model == 'notransport':
        x, St = solve_notransport(alpha, prm, x0, xf, N, scheme)
    elif model == 'covariant':
        x, St = solve_covariant(alpha, prm, x0, xf, N, scheme)
    else:
        raise ValueError(model)
    return x, St
